### ISSUE TITLE
空指针 一节中的一些错误

### ISSUE THREAD

**Issue by timothyqiu** [neuront/cpp11book#1]
钻几个牛角尖，不要打我 >_< ~

---

> 作为最早引入 "指针" 这一概念的语言, C 和 C++ 中……

如果根据[维基百科](https://en.wikipedia.org/wiki/Pointer_(computer_programming)#History)，「指针」的概念是 1964 年首次被提出并在 PL/I 语言中实现的。

> 用户一般会用 `NULL` 来表示空指针, 但它并不是关键字, 而是一个宏, 在 C 中它被定义为 `(void*)0`, 而 C++ 中…… `NULL` 的定义也变为了字面量 0.

C 语言历代[标准](http://port70.net/~nsz/c/c89/c89-draft.html#4.1.5)里 `NULL` 都是「实现定义的空指针常量」，而空指针常量是「值为 0 的整型常量表达式，或被转换为 `void *` 型的这样的表达式」。所以 `0` 和 `(void *) 0` 都是 C 语言里合法、[常见](http://c-faq.com/null/macro.html)的 `NULL`，并不是到了 C++ 才改变的。

> 不过, `NULL` 宏的定义并没有被直接改成这一关键字

C++11 前后对 `NULL` 的要求一直是「实现定义的空指针常量」没有变，但是「空指针常量」的概念扩大了范围，加入了 `nullptr_t` 的值。所以并不是 `NULL` 的定义没有改变，而是标准允许不改变，而绝大多数编译器可能出于兼容考虑而选择维持现状。<sup>[ref](https://stackoverflow.com/a/7200762/438720)</sup>

---

涉及标准 / 实现的东西如果真的写进去可能会比较啰嗦，仅供参考 🍺

**Comment by zheplusplus** [comment]
谢谢指出.

书写方针上还是希望接地气一点, 不把标准照搬到文章里而是用被实现的方案来叙述. 这样的话就考虑在文中加上 "常见编译器的实现方案是..." 以免报道上出现偏差将来负责任 (

不过确认了一下好像 gcc 自带的头文件里的 `NULL` 定义不是 0 而是自定义的关键字, 我都改掉好了.

话说你发 issue 时 Github 创建的邮件名字不是 timothyqiu 而是 Haoyu Qiu 突然没认出来 `_(:3J<)_`

**Comment by timothyqiu** [comment]
哈哈～很多教科书为了避免不必要的复杂确实也会避免说很多细节「现在可以公开的情报」😄
